import * as Yup from 'yup'
import { FieldConfig } from '../Master/ItemsConfig'

export const POMasterConfig: FieldConfig[] = [
  {
    id: 'TransactionType',
    label: 'Transaction Type',
    type: 'text',
    required: true,
    initialValue: 'Purchase Order',
    validation: Yup.string(),
    readOnly: true,
  },
  {
    id: 'TransactionNumber',
    label: 'PO Number',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('po Number is required'),
  },
  {
    id: 'TransactionDate',
    label: 'Transaction Date',
    type: 'date',
    required: true,
    initialValue: '',
    validation: Yup.date().required('Transaction Date is required'),
  },
  {
    id: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    options: ['Open', 'Approved', 'Close', 'other'],
    initialValue: 'Open',
    validation: Yup.string(),
  },
  {
    id: 'Remarks',
    label: 'Remarks',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Remarks is required'),
  },
]

export const PODetailsConfig: FieldConfig[] = [
  {
    id: 'ItemType',
    label: 'Item Type',
    type: 'select',
    required: false,
    initialValue: 'FG',
    options: ['FG (Finished Goods)', 'RM (Raw Material)', 'Other'],
    validation: Yup.string(),
  },
  {
    id: 'ItemDescription',
    label: 'Item Description',
    type: 'textarea',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Item Description is required'),
  },
  {
    id: 'Quantity',
    label: 'Quantity',
    type: 'number',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Quantity is required'),
  },
  {
    id: 'UnitOfMeasure',
    label: 'UOM',
    type: 'select',
    required: false,
    options: ['KG', 'Box'],
    initialValue: 'KG',
    validation: Yup.string(),
  },
  {
    id: 'UnitPrice',
    label: 'Unit Price',
    type: 'number',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'DiscountPercentage',
    label: 'Discount Percentage',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'TaxPercentage',
    label: 'Tax Percentage',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'TotalPrice',
    label: 'Total Price',
    type: 'number',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'DeliveryDate',
    label: 'Delivery Date',
    type: 'date',
    required: false,
    initialValue: '',
    validation: Yup.date(),
  },
  {
    id: 'LotNumber',
    label: 'Lot Number',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
]
