import * as Yup from 'yup'
import { FieldConfig } from './ItemsConfig'

const customerFieldsConfig: FieldConfig[] = [
  {
    id: 'customerName',
    label: 'Customer Name',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Customer Name is required'),
  },
  {
    id: 'contactPerson',
    label: 'Contact Person',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Contact Person is required'),
  },
  {
    id: 'contactInformation',
    label: 'Contact Information',
    type: 'textarea',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Contact Information is required'),
  },
  {
    id: 'email',
    label: 'Email Address',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().email('Invalid email address').required('Email is required'),
  },
  {
    id: 'phoneNumber',
    label: 'Phone Number',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Phone Number is required'),
  },
  {
    id: 'billingAddress',
    label: 'Billing Address',
    type: 'textarea',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Billing Address is required'),
  },
  {
    id: 'shippingAddresses',
    label: 'Shipping Address(es)',
    type: 'textarea',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Shipping Address is required'),
  },
  {
    id: 'customerCategory',
    label: 'Customer Category',
    type: 'select',
    required: true,
    options: ['Retail', 'Wholesale', 'Corporate', 'Government', 'Other'],
    initialValue: '',
    validation: Yup.string().required('Customer Category is required'),
  },
  {
    id: 'taxInformation',
    label: 'Tax Information (GST/VAT)',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Tax Information is required'),
  },
  {
    id: 'customerSince',
    label: 'Customer Since',
    type: 'date',
    required: true,
    initialValue: '',
    validation: Yup.date().required('Customer Since date is required'),
  },
  {
    id: 'bankName',
    label: 'Bank Name',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'ifscCode',
    label: 'IFSC Code',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'creditLimit',
    label: 'Credit Limit',
    type: 'number',
    required: false,
    initialValue: '',
    validation: Yup.number().min(0, 'Credit Limit must be non-negative'),
  },
  {
    id: 'paymentTerms',
    label: 'Payment Terms',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    options: ['Active', 'Inactive', 'On Hold', 'Blacklisted'],
    initialValue: 'Active',
    validation: Yup.string().required('Status is required'),
  },
]

export default customerFieldsConfig
