import * as Yup from 'yup'
import { FieldConfig } from './ItemsConfig'

const designMasterFieldsConfig: FieldConfig[] = [
  {
    id: 'designName',
    label: 'Design Name',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Design Name is required'),
  },
  {
    id: 'designType',
    label: 'Design Type',
    type: 'select',
    required: true,
    options: ['Sticker', 'Printed'],
    initialValue: 'Sticker',
    validation: Yup.string().required('Please choose the design type'),
  },
  {
    id: 'creationDate',
    label: 'Creation Date',
    type: 'date',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Creation Date is required'),
  },
  {
    id: 'designOwner',
    label: 'Design Owner (Self/Customer)',
    type: 'select',
    required: true,
    options: ['Self', 'Customer'],
    initialValue: 'Self',
    validation: Yup.string().required('Please choose a option'),
  },
  {
    id: 'technicalSpecifications',
    label: 'Technical Specifications',
    type: 'textarea',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'designFiles',
    label: 'Design Files',
    type: 'file',
    required: true,
    initialValue: '',
    validation: Yup.string().required('Design File is required'),
  },
  {
    id: 'customerId',
    label: 'Customer Id',
    type: 'text',
    required: true,
    initialValue: '',
    validation: Yup.string().required('customer Id is required'),
  },
  {
    id: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    options: ['Active', 'InActive'],
    initialValue: 'Active',
    validation: Yup.string().required('Status is required'),
  },
  {
    id: 'season',
    label: 'Season',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string(),
  },
  {
    id: 'sizes',
    label: 'Sizes',
    type: 'select',
    required: true,
    options: ['sm', 'lg', 'xl', 'xxl', 'xxxl'],
    initialValue: 'sm',
    validation: Yup.string().required('Size is required'),
  },
  {
    id: 'category',
    label: 'Category',
    type: 'select',
    required: true,
    options: ['yarn', 'silk', 'cotton', 'jute', 'wool'],
    initialValue: 'Yarn',
    validation: Yup.string().required('category is required'),
  },
  {
    id: 'artName',
    label: 'Art Name',
    type: 'text',
    required: false,
    initialValue: '',
    validation: Yup.string().required('Art Name is required'),
  },
]

export default designMasterFieldsConfig
